version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: dbapp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    command: 
      --init-file /init.sql
    volumes:
      - data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"

volumes:
  data: