version: '3.1'

services:
  db:
    image: mysql:8.0
    container_name: dbapp
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    command: 
      --init-file /init.sql
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/init.sql
      - ./custom.conf:/etc/mysql/conf.d
    expose:
      - "3306"
    ports:
      - "3309:3306"

  redis:
    image: redis:8-alpine
    container_name: redisapp
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --requirepass redispassword

volumes:
  mysql_data:
  redis_data: